name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo -e "Host server\n\tHostName ${{ secrets.EC2_HOST }}\n\tUser ubuntu\n\tIdentityFile ~/.ssh/deploy_key\n\tStrictHostKeyChecking no" > ~/.ssh/config

      - name: Deploy to Server
        run: |
          ssh server '
            cd fastapi-book-project
            git fetch origin main
            git reset --hard origin/main
            source env/bin/activate
            pip install --no-cache-dir -r requirements.txt
            sudo systemctl restart fastapi 
          '