name: CD pipeline
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ubuntu
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            cd /home/ubuntu/fastapi-app || exit 1
            git pull origin main || exit 1
            source venv/bin/activate
            pip install -r requirements.txt || exit 1
            sudo systemctl restart fastapi || exit 1
            sudo systemctl restart nginx || exit 1

